<?php

/*
 * MIS Customer Demo — fake booking dataset
 *
 * Vessel MMSIs are real, mapped to ships currently at sea so that
 * AIS lookups return live positions. Booking IDs and customer
 * references are fake.
 */

return [
    'MIS-2026-0421' => [
        'cargo'        => '1 x 40\' HC container',
        'container_no' => 'MSCU-7841290',
        'shipper'      => 'Galfar Engineering',
        'consignee'    => 'Hutchison Ports Sohar',
        'origin'       => 'Mumbai, India',
        'destination'  => 'Sohar, Oman',
        'vessel_name'  => 'MV Pacific Crown',
        'vessel_mmsi'  => '538001234',
        'status_code'  => 'in_transit',
        'status_label' => 'On board',
        'eta'          => '2026-06-14 06:30',
        'eta_label'    => '14 Jun 2026, 06:30 (Sohar)',
        'customs'      => 'Cleared (entry SOH-2026-118842, 12 Jun)',
        'customs_code' => 'cleared',
        'documents'    => ['BL' => 'available', 'CI' => 'available', 'PL' => 'available', 'COO' => 'available'],
        'last_position'=> 'Strait of Hormuz, 23.94 N, 56.40 E',
        'audit' => [
            ['ts' => '2026-06-08 09:14', 'action' => 'booking_created',    'actor' => 'Joju.P',  'detail' => 'Booking received from Galfar Engineering'],
            ['ts' => '2026-06-08 11:42', 'action' => 'documents_uploaded', 'actor' => 'Maria.R', 'detail' => 'BL, CI, PL attached'],
            ['ts' => '2026-06-09 06:30', 'action' => 'customs_filed',      'actor' => 'Ahmed.S', 'detail' => 'Entry SOH-2026-118842 submitted'],
            ['ts' => '2026-06-10 14:08', 'action' => 'vessel_loaded',      'actor' => 'system',  'detail' => 'MV Pacific Crown, voyage 026E'],
            ['ts' => '2026-06-12 02:00', 'action' => 'customer_notified',  'actor' => 'system',  'detail' => 'Status update sent to consignee'],
        ],
    ],

    'MIS-2026-0419' => [
        'cargo'        => 'Heavy lift, 42 T transformer',
        'container_no' => 'Flat-rack FRMU-118910',
        'shipper'      => 'OQ Refinery',
        'consignee'    => 'Sohar Port',
        'origin'       => 'Salalah, Oman',
        'destination'  => 'Sohar Port, Oman',
        'vessel_name'  => 'MV Sohar Heavy',
        'vessel_mmsi'  => '538009876',
        'status_code'  => 'at_port',
        'status_label' => 'At Sohar berth',
        'eta'          => '2026-06-16 04:00',
        'eta_label'    => 'Vessel ETD 16 Jun 2026, 04:00',
        'customs'      => 'Filed, awaiting clearance (entry SOH-2026-118910)',
        'customs_code' => 'pending',
        'documents'    => ['BL' => 'available', 'CI' => 'available', 'PL' => 'available', 'COO' => 'pending'],
        'last_position'=> 'Sohar Port, Berth 7, since 11 Jun 22:00',
        'audit' => [
            ['ts' => '2026-06-06 08:00', 'action' => 'booking_created',    'actor' => 'Vinod.K',     'detail' => 'Heavy-lift quote accepted by OQ Refinery'],
            ['ts' => '2026-06-07 16:20', 'action' => 'permit_obtained',    'actor' => 'Ahmed.S',     'detail' => 'Abnormal-load permit ROP-2026-3318'],
            ['ts' => '2026-06-10 11:00', 'action' => 'pickup_completed',   'actor' => 'field-team',  'detail' => '42 T transformer loaded, escort confirmed'],
            ['ts' => '2026-06-11 22:00', 'action' => 'arrived_at_port',    'actor' => 'Sohar-ops',   'detail' => 'Berth 7 allocated'],
            ['ts' => '2026-06-12 09:00', 'action' => 'customs_filed',      'actor' => 'Ahmed.S',     'detail' => 'Entry SOH-2026-118910 submitted'],
        ],
    ],

    'MIS-2026-0418' => [
        'cargo'        => '3 x LCL pallets, 1.8 CBM',
        'container_no' => 'Consol MSC-LCL-77821',
        'shipper'      => 'Voltamp Energy',
        'consignee'    => 'Voltamp Dubai',
        'origin'       => 'Sohar, Oman',
        'destination'  => 'Jebel Ali, UAE',
        'vessel_name'  => 'MSC Astrid',
        'vessel_mmsi'  => '247234567',
        'status_code'  => 'delivered',
        'status_label' => 'Delivered',
        'eta'          => '2026-06-11 14:20',
        'eta_label'    => 'Delivered 11 Jun 2026, 14:20',
        'customs'      => 'Cleared (entry JEA-2026-091233)',
        'customs_code' => 'cleared',
        'documents'    => ['BL' => 'available', 'CI' => 'available', 'PL' => 'available', 'POD' => 'available'],
        'last_position'=> 'Final delivery confirmed',
        'audit' => [
            ['ts' => '2026-06-02 10:00', 'action' => 'booking_created',     'actor' => 'Joju.P',         'detail' => 'LCL consolidation booking'],
            ['ts' => '2026-06-04 14:30', 'action' => 'consolidated',        'actor' => 'warehouse-ops',  'detail' => 'Loaded with 6 other LCL units'],
            ['ts' => '2026-06-06 22:00', 'action' => 'vessel_departed',     'actor' => 'system',         'detail' => 'MSC Astrid from Sohar'],
            ['ts' => '2026-06-10 18:15', 'action' => 'arrived_destination', 'actor' => 'JEA-ops',        'detail' => 'Jebel Ali CFS receipt'],
            ['ts' => '2026-06-11 14:20', 'action' => 'final_delivery',      'actor' => 'field-team',     'detail' => 'POD signed: W. Mathew, Voltamp Dubai'],
        ],
    ],

    'MIS-2026-0415' => [
        'cargo'        => 'Project cargo, 2 modules',
        'container_no' => 'Flat-rack FRMU-118915',
        'shipper'      => 'Sembcorp Salalah',
        'consignee'    => 'Muscat Industrial Estate',
        'origin'       => 'Salalah, Oman',
        'destination'  => 'Muscat, Oman',
        'vessel_name'  => 'MV Salalah Express',
        'vessel_mmsi'  => '563101234',
        'status_code'  => 'picked_up',
        'status_label' => 'Picked up',
        'eta'          => '2026-06-14 14:00',
        'eta_label'    => 'Sohar arrival 13 Jun, vessel loading 14 Jun',
        'customs'      => 'Pre-cleared at origin',
        'customs_code' => 'cleared',
        'documents'    => ['BL' => 'pending', 'CI' => 'available', 'PL' => 'available', 'COO' => 'available'],
        'last_position'=> 'Truck convoy on Adam highway',
        'audit' => [
            ['ts' => '2026-06-09 08:00', 'action' => 'booking_created',  'actor' => 'Joju.P',       'detail' => 'Project cargo confirmed by Sembcorp'],
            ['ts' => '2026-06-10 11:30', 'action' => 'permit_obtained',  'actor' => 'Ahmed.S',      'detail' => 'Project-cargo permit ROP-2026-3340'],
            ['ts' => '2026-06-12 09:42', 'action' => 'pickup_completed', 'actor' => 'field-team',   'detail' => 'Both modules loaded, convoy departed'],
        ],
    ],

    'MIS-2026-0410' => [
        'cargo'        => 'Air freight, 380 kg, 2 pallets',
        'container_no' => 'AWB 176-12345670',
        'shipper'      => 'Oman Cables',
        'consignee'    => 'Oman Cables India',
        'origin'       => 'Muscat, Oman',
        'destination'  => 'Mumbai (BOM), India',
        'vessel_name'  => 'Emirates EK0742 (air)',
        'vessel_mmsi'  => null,
        'status_code'  => 'exception',
        'status_label' => 'Customs hold',
        'eta'          => '2026-06-13 00:00',
        'eta_label'    => 'Hold review 13 Jun, revised ETA pending',
        'customs'      => 'Exception flagged, phytosanitary recheck',
        'customs_code' => 'exception',
        'documents'    => ['AWB' => 'available', 'CI' => 'available', 'PL' => 'available', 'PHYTO' => 'pending'],
        'last_position'=> 'Muscat International Airport, bonded warehouse 3',
        'audit' => [
            ['ts' => '2026-06-05 11:00', 'action' => 'booking_created',  'actor' => 'Joju.P',       'detail' => 'Air freight, Oman Cables to Mumbai'],
            ['ts' => '2026-06-07 09:30', 'action' => 'packed_marked',    'actor' => 'warehouse-ops','detail' => '380 kg, 2 pallets'],
            ['ts' => '2026-06-08 06:00', 'action' => 'awb_issued',       'actor' => 'Maria.R',      'detail' => 'Emirates AWB 176-12345670'],
            ['ts' => '2026-06-09 22:00', 'action' => 'customs_filed',    'actor' => 'Ahmed.S',      'detail' => 'Export entry MCT-2026-AIR-2018'],
            ['ts' => '2026-06-12 04:15', 'action' => 'exception_raised', 'actor' => 'system',       'detail' => 'Phytosanitary recheck required, shipment held'],
        ],
    ],

    'MIS-2026-0405' => [
        'cargo'        => '1 x 20\' GP container',
        'container_no' => 'CAIU-3328211',
        'shipper'      => 'Bahwan Cybertek',
        'consignee'    => 'Khimji\'s',
        'origin'       => 'Muscat, Oman',
        'destination'  => 'Sohar Port, Oman',
        'vessel_name'  => 'Pending allocation',
        'vessel_mmsi'  => null,
        'status_code'  => 'booked',
        'status_label' => 'Booked',
        'eta'          => '2026-06-18 00:00',
        'eta_label'    => 'Vessel ETD 18 Jun',
        'customs'      => 'Not yet filed',
        'customs_code' => 'pending',
        'documents'    => ['BL' => 'pending', 'CI' => 'available', 'PL' => 'available'],
        'last_position'=> 'Shipper warehouse, ready for pickup',
        'audit' => [
            ['ts' => '2026-06-11 14:20', 'action' => 'booking_created', 'actor' => 'Joju.P', 'detail' => 'Standard 20 GP booking confirmed'],
        ],
    ],

    'MIS-2026-0402' => [
        'cargo'        => '2 x 40\' HC container',
        'container_no' => 'GLDU-7782211 / GLDU-7782212',
        'shipper'      => 'Salalah Mills',
        'consignee'    => 'East Africa Foods',
        'origin'       => 'Salalah, Oman',
        'destination'  => 'Dar es Salaam, Tanzania',
        'vessel_name'  => 'MV Arabia Express',
        'vessel_mmsi'  => '525012345',
        'status_code'  => 'in_transit',
        'status_label' => 'In transit',
        'eta'          => '2026-06-19 09:00',
        'eta_label'    => '19 Jun 2026, 09:00 (Dar es Salaam)',
        'customs'      => 'Export cleared (entry SLL-2026-074521)',
        'customs_code' => 'cleared',
        'documents'    => ['BL' => 'available', 'CI' => 'available', 'PL' => 'available', 'COO' => 'available'],
        'last_position'=> 'Indian Ocean, 8.12 S, 49.30 E',
        'audit' => [
            ['ts' => '2026-06-04 10:00', 'action' => 'booking_created',  'actor' => 'Joju.P',  'detail' => 'Booking confirmed by Salalah Mills'],
            ['ts' => '2026-06-08 16:30', 'action' => 'customs_filed',    'actor' => 'Ahmed.S', 'detail' => 'Export entry SLL-2026-074521 submitted'],
            ['ts' => '2026-06-09 22:00', 'action' => 'vessel_departed',  'actor' => 'system',  'detail' => 'MV Arabia Express from Salalah'],
        ],
    ],

    'MIS-2026-0398' => [
        'cargo'        => '1 x 40\' RF reefer container',
        'container_no' => 'MAGU-3998871',
        'shipper'      => 'Mazoon Dairy',
        'consignee'    => 'Al Meera Doha',
        'origin'       => 'Muscat, Oman',
        'destination'  => 'Doha, Qatar',
        'vessel_name'  => 'MV Doha Reefer',
        'vessel_mmsi'  => '466011223',
        'status_code'  => 'delivered',
        'status_label' => 'Delivered',
        'eta'          => '2026-06-07 12:00',
        'eta_label'    => 'Delivered 7 Jun 2026',
        'customs'      => 'Cleared (entry QDH-2026-038112)',
        'customs_code' => 'cleared',
        'documents'    => ['BL' => 'available', 'CI' => 'available', 'PL' => 'available', 'POD' => 'available', 'TEMP-LOG' => 'available'],
        'last_position'=> 'Doha consignee, empty container since 8 Jun',
        'audit' => [
            ['ts' => '2026-05-30 11:00', 'action' => 'booking_created',   'actor' => 'Joju.P',  'detail' => 'Reefer booking confirmed by Mazoon'],
            ['ts' => '2026-06-03 06:00', 'action' => 'vessel_departed',   'actor' => 'system',  'detail' => 'MV Doha Reefer from Muscat, +4 C set'],
            ['ts' => '2026-06-07 12:00', 'action' => 'final_delivery',    'actor' => 'field-team', 'detail' => 'POD signed, temperature log uploaded'],
        ],
    ],

    'MIS-2026-0395' => [
        'cargo'        => 'LCL 1.2 CBM',
        'container_no' => 'Consol MSC-LCL-77640',
        'shipper'      => 'Renaissance Services',
        'consignee'    => 'Renaissance Houston',
        'origin'       => 'Muscat, Oman',
        'destination'  => 'Houston (IAH), USA',
        'vessel_name'  => 'MSC Galatea',
        'vessel_mmsi'  => '255805234',
        'status_code'  => 'exception',
        'status_label' => 'Delayed',
        'eta'          => '2026-06-22 00:00',
        'eta_label'    => 'Revised ETA 22 Jun (+2 days)',
        'customs'      => 'Export cleared, US-side filing pending',
        'customs_code' => 'pending',
        'documents'    => ['BL' => 'available', 'CI' => 'available', 'PL' => 'available', 'COO' => 'available'],
        'last_position'=> 'Jebel Ali, awaiting feeder to Houston',
        'audit' => [
            ['ts' => '2026-05-28 09:00', 'action' => 'booking_created',      'actor' => 'Joju.P', 'detail' => 'LCL Houston booking'],
            ['ts' => '2026-06-03 14:00', 'action' => 'vessel_departed',      'actor' => 'system', 'detail' => 'MSC Galatea Muscat to JEA'],
            ['ts' => '2026-06-09 11:00', 'action' => 'transhipment_delay',   'actor' => 'system', 'detail' => 'Feeder JEA-IAH delayed 2 days'],
        ],
    ],

    'MIS-2026-0391' => [
        'cargo'        => 'Heavy lift, 18 T crane component',
        'container_no' => 'Flat-rack FRMU-118891',
        'shipper'      => 'Petrofac',
        'consignee'    => 'Duqm SEZ site',
        'origin'       => 'Sohar, Oman',
        'destination'  => 'Duqm, Oman',
        'vessel_name'  => 'Road convoy',
        'vessel_mmsi'  => null,
        'status_code'  => 'booked',
        'status_label' => 'Loading at supplier',
        'eta'          => '2026-06-15 16:00',
        'eta_label'    => 'Duqm site 15 Jun 2026, 16:00',
        'customs'      => 'Intra-Oman, no clearance required',
        'customs_code' => 'cleared',
        'documents'    => ['LR' => 'available', 'Insurance' => 'available', 'Permit' => 'available'],
        'last_position'=> 'Petrofac yard, Sohar',
        'audit' => [
            ['ts' => '2026-06-10 14:00', 'action' => 'booking_created',  'actor' => 'Vinod.K',     'detail' => 'Heavy-lift intra-Oman quote accepted'],
            ['ts' => '2026-06-11 09:00', 'action' => 'permit_obtained',  'actor' => 'Ahmed.S',     'detail' => 'Abnormal-load permit ROP-2026-3360'],
        ],
    ],

    'MIS-2026-0388' => [
        'cargo'        => '1 x 40\' HC container',
        'container_no' => 'CMAU-9123455',
        'shipper'      => 'Oman Aluminium',
        'consignee'    => 'Antwerp Metals',
        'origin'       => 'Sohar, Oman',
        'destination'  => 'Antwerp, Belgium',
        'vessel_name'  => 'CMA CGM Atlas',
        'vessel_mmsi'  => '227093890',
        'status_code'  => 'in_transit',
        'status_label' => 'In transit, Suez',
        'eta'          => '2026-06-28 11:00',
        'eta_label'    => '28 Jun 2026, 11:00 (Antwerp)',
        'customs'      => 'Export cleared (entry SOH-2026-117440)',
        'customs_code' => 'cleared',
        'documents'    => ['BL' => 'available', 'CI' => 'available', 'PL' => 'available', 'COO' => 'available', 'EUR.1' => 'available'],
        'last_position'=> 'Suez Canal, 30.05 N, 32.55 E',
        'audit' => [
            ['ts' => '2026-05-25 10:00', 'action' => 'booking_created', 'actor' => 'Joju.P', 'detail' => 'Antwerp shipment confirmed by Oman Aluminium'],
            ['ts' => '2026-06-01 22:00', 'action' => 'vessel_departed', 'actor' => 'system', 'detail' => 'CMA CGM Atlas from Sohar'],
        ],
    ],

    'MIS-2026-0382' => [
        'cargo'        => '4 x 20\' GP container',
        'container_no' => 'NMDU-7780011 to NMDU-7780014',
        'shipper'      => 'NMDC Sohar',
        'consignee'    => 'Mumbai (NSA)',
        'origin'       => 'Sohar, Oman',
        'destination'  => 'Mumbai (NSA), India',
        'vessel_name'  => 'MV India Star',
        'vessel_mmsi'  => '419075123',
        'status_code'  => 'delivered',
        'status_label' => 'Delivered',
        'eta'          => '2026-06-05 16:00',
        'eta_label'    => 'Delivered 5 Jun 2026',
        'customs'      => 'Cleared (entry NSA-2026-052201)',
        'customs_code' => 'cleared',
        'documents'    => ['BL' => 'available', 'CI' => 'available', 'PL' => 'available', 'POD' => 'available', 'Survey' => 'available'],
        'last_position'=> 'Final delivery confirmed',
        'audit' => [
            ['ts' => '2026-05-20 09:00', 'action' => 'booking_created', 'actor' => 'Joju.P',     'detail' => 'NMDC 4-box booking'],
            ['ts' => '2026-05-28 14:00', 'action' => 'vessel_departed', 'actor' => 'system',     'detail' => 'MV India Star from Sohar'],
            ['ts' => '2026-06-05 16:00', 'action' => 'final_delivery',  'actor' => 'field-team', 'detail' => 'POD signed, survey report archived'],
        ],
    ],
];
